In [66]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
cooperunion_anime_recommendations_database_path = kagglehub.dataset_download('CooperUnion/anime-recommendations-database')

print('Data source import complete.')

Using Colab cache for faster access to the 'anime-recommendations-database' dataset.
Data source import complete.

In [67]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/anime-recommendations-database/rating.csv
/kaggle/input/anime-recommendations-database/anime.csv

In [68]:
import os
anime=pd.read_csv(os.path.join(cooperunion_anime_recommendations_database_path, 'anime.csv'))
rating=pd.read_csv(os.path.join(cooperunion_anime_recommendations_database_path, 'rating.csv'))

In [69]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [70]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [71]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [72]:
anime['rating']=anime['rating'].fillna(anime['rating'].mean())

In [73]:
anime=anime.dropna()

In [74]:
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [75]:
anime.duplicated().sum()

np.int64(0)

In [76]:
anime['tags']=anime['genre']+","+anime['type']

/tmp/ipykernel_12074/60458773.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime['tags']=anime['genre']+","+anime['type']

In [77]:
anime

,anime_id,name,genre,type,episodes,rating,members,tags
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,"Drama, Romance, School, Supernatural,Movie"
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665,"Action, Adventure, Drama, Fantasy, Magic, Mili..."
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262,"Action, Comedy, Historical, Parody, Samurai, S..."
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572,"Sci-Fi, Thriller,TV"
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266,"Action, Comedy, Historical, Parody, Samurai, S..."
...,...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211,"Hentai,OVA"
12290,5543,Under World,Hentai,OVA,1,4.28,183,"Hentai,OVA"
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219,"Hentai,OVA"
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,"Hentai,OVA"
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,"Hentai,Movie"

In [78]:
from nltk.stem.porter import PorterStemmer

In [79]:
ps=PorterStemmer()

In [80]:
def stem(obj):
    y=[]
    for i in obj.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [81]:
ps.stem('adventure')

'adventur'

In [82]:
new_anime=anime[['anime_id','name',	'tags']]

In [83]:
new_anime['tags']=new_anime['tags'].apply(stem)

/tmp/ipykernel_12074/350771864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_anime['tags']=new_anime['tags'].apply(stem)

In [84]:
new_anime.head()

,anime_id,name,tags
0,32281,Kimi no Na wa.,"drama, romance, school, supernatural,movi"
1,5114,Fullmetal Alchemist: Brotherhood,"action, adventure, drama, fantasy, magic, mili..."
2,28977,Gintama°,"action, comedy, historical, parody, samurai, s..."
3,9253,Steins;Gate,"sci-fi, thriller,tv"
4,9969,Gintama&#039;,"action, comedy, historical, parody, samurai, s..."

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)

In [86]:
vectors=cv.fit_transform(anime['tags']).toarray()

In [87]:
cv.get_feature_names_out()

array(['action', 'adventure', 'ai', 'arts', 'cars', 'comedy', 'dementia',
       'demons', 'drama', 'ecchi', 'fantasy', 'fi', 'game', 'harem',
       'hentai', 'historical', 'horror', 'josei', 'kids', 'life', 'magic',
       'martial', 'mecha', 'military', 'movie', 'music', 'mystery', 'of',
       'ona', 'ova', 'parody', 'police', 'power', 'psychological',
       'romance', 'samurai', 'school', 'sci', 'seinen', 'shoujo',
       'shounen', 'slice', 'space', 'special', 'sports', 'super',
       'supernatural', 'thriller', 'tv', 'vampire', 'yaoi', 'yuri'],
      dtype=object)

In [88]:
from sklearn.metrics.pairwise import cosine_similarity

In [89]:
cosine_similarity(vectors)

array([[1.        , 0.15811388, 0.        , ..., 0.        , 0.        ,
        0.31622777],
       [0.15811388, 1.        , 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.35355339, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.31622777, 0.        , 0.        , ..., 0.5       , 0.5       ,
        1.        ]])

In [90]:
cosine_similarity(vectors).shape

(12210, 12210)

In [91]:
similarity=cosine_similarity(vectors)

In [92]:
similarity[0]

array([1.        , 0.15811388, 0.        , ..., 0.        , 0.        ,
       0.31622777])

In [93]:
reco_anime=new_anime[new_anime['name']=='Fullmetal Alchemist: Brotherhood'].index[0]

In [94]:
def recommend_anime_smart(user_input, top_n=5):
    print(f"Searching for recommendations for: '{user_input}'")

    # Try to find an exact match for an anime name (case-insensitive)
    matched_anime = new_anime[new_anime['name'].str.lower() == user_input.lower()]

    if not matched_anime.empty:
        anime_index = matched_anime.index[0]
        distances = similarity[anime_index]
        movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:top_n + 1] # +1 to exclude itself
        print(f"Recommendations based on anime '{matched_anime.iloc[0]['name']}':")
    else:
        print(f"Anime '{user_input}' not found. Providing recommendations based on input description.")
        stemmed_input = stem(user_input.lower())
        input_vector = cv.transform([stemmed_input]).toarray()
        distances = cosine_similarity(input_vector, vectors)[0]
        movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[:top_n]
        print(f"Recommendations based on description '{user_input}':")

    for i, score in movies_list:
        print(f"- {new_anime.iloc[i]['name']} (Similarity: {score:.2f})")

Now, let's try the new recommendation function with a custom input.

In [95]:
recommend_anime_smart('naruto')
print("\n")
recommend_anime_smart('Fullmetal Alchemist: Brotherhood')
print("\n")
recommend_anime_smart('Sci-fi thriller movie about space')
print("\n")
recommend_anime_smart('')

Searching for recommendations for: 'naruto'
Recommendations based on anime 'Naruto':
- Naruto (Similarity: 1.00)
- Dragon Ball Z (Similarity: 0.89)
- Dragon Ball Kai (2014) (Similarity: 0.89)
- Dragon Ball Kai (Similarity: 0.89)
- Medaka Box Abnormal (Similarity: 0.89)


Searching for recommendations for: 'Fullmetal Alchemist: Brotherhood'
Recommendations based on anime 'Fullmetal Alchemist: Brotherhood':
- Fullmetal Alchemist (Similarity: 0.94)
- Magi: The Kingdom of Magic (Similarity: 0.87)
- Magi: The Labyrinth of Magic (Similarity: 0.87)
- Magi: Sinbad no Bouken (TV) (Similarity: 0.87)
- Densetsu no Yuusha no Densetsu (Similarity: 0.87)


Searching for recommendations for: 'Sci-fi thriller movie about space'
Anime 'Sci-fi thriller movie about space' not found. Providing recommendations based on input description.
Recommendations based on description 'Sci-fi thriller movie about space':
- Steins;Gate (Similarity: 0.75)
- Steins;Gate Movie: Fuka Ryouiki no Déjà vu (Similarity: 0.75)
- Steins;Gate: Oukoubakko no Poriomania (Similarity: 0.75)
- Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero (Similarity: 0.75)
- Mouretsu Pirates: Abyss of Hyperspace (Similarity: 0.75)


Searching for recommendations for: ''
Anime '' not found. Providing recommendations based on input description.
Recommendations based on description '':
- Kimi no Na wa. (Similarity: 0.00)
- Fullmetal Alchemist: Brotherhood (Similarity: 0.00)
- Gintama° (Similarity: 0.00)
- Steins;Gate (Similarity: 0.00)
- Gintama&#039; (Similarity: 0.00)

In [100]:
search_term = 'naruto'
found_titles = new_anime[new_anime['name'].str.contains(search_term, case=False, na=False)]

if not found_titles.empty:
    print(f"Found {len(found_titles)} titles matching '{search_term}':")
    for title in found_titles['name'].unique():
        print(title)
else:
    print(f"No titles found containing '{search_term}'. Please try a different search term or check the dataset.")

Found 25 titles matching 'naruto':
Boruto: Naruto the Movie
Naruto: Shippuuden
The Last: Naruto the Movie
Naruto: Shippuuden Movie 6 - Road to Ninja
Naruto
Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi
Naruto: Shippuuden Movie 5 - Blood Prison
Naruto x UT
Naruto: Shippuuden Movie 4 - The Lost Tower
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono
Naruto: Shippuuden Movie 1
Naruto: Shippuuden Movie 2 - Kizuna
Naruto Shippuuden: Shippuu! &quot;Konoha Gakuen&quot; Den
Naruto: Honoo no Chuunin Shiken! Naruto vs. Konohamaru!!
Naruto SD: Rock Lee no Seishun Full-Power Ninden
Naruto Shippuuden: Sunny Side Battle
Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!
Naruto Soyokazeden Movie: Naruto to Mashin to Mitsu no Onegai Dattebayo!!
Naruto Movie 2: Dai Gekitotsu! Maboroshi no Chiteiiseki Dattebayo!
Naruto: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo! Special: Konoha Annual Sports Festival
Naruto Movie 3: Dai Koufun! Mikazuki Jima no Animaru Panikku Dattebayo!
Naruto: The Cross Roads
Naruto Narutimate Hero 3: Tsuini Gekitotsu! Jounin vs. Genin!! Musabetsu Dairansen taikai Kaisai!!
Naruto: Takigakure no Shitou - Ore ga Eiyuu Dattebayo!
Naruto: Akaki Yotsuba no Clover wo Sagase

In [99]:
recommend_anime_smart('naruto')

Searching for recommendations for: 'naruto'
Recommendations based on anime 'Naruto':
- Naruto (Similarity: 1.00)
- Dragon Ball Z (Similarity: 0.89)
- Dragon Ball Kai (2014) (Similarity: 0.89)
- Dragon Ball Kai (Similarity: 0.89)
- Medaka Box Abnormal (Similarity: 0.89)